### ISSUE TITLE
Slide Typography

### ISSUE THREAD

**Issue by una** [una/slides-SXSW-2015#1]
Including 
- headers
- paragraphs
- lists

**Comment by ryanbrownhill** [comment]
Update
* Headers I kept the same - Magnel. 
* I have changed the Body text to the sans-serif typeface Nexa Thin.
* List changed with the Body text - so also Nexa Thin. Didn't feel the need for an additional typeface.

**Comment by una** [comment]
can you please screenshot how they look now? thank you! :+1:

**Comment by ryanbrownhill** [comment]
![screen shot 2015-02-23 at 1 57 03 pm](https://cloud.githubusercontent.com/assets/9538395/6335842/f8f4f9e0-bb63-11e4-9c40-ed4dd7457d8a.png)
![screen shot 2015-02-23 at 1 57 15 pm](https://cloud.githubusercontent.com/assets/9538395/6335844/f8f5751e-bb63-11e4-9568-639ff9f51826.png)
![screen shot 2015-02-23 at 1 57 37 pm](https://cloud.githubusercontent.com/assets/9538395/6335843/f8f4ec66-bb63-11e4-80fe-b7aae42989e6.png)
![screen shot 2015-02-23 at 1 58 06 pm](https://cloud.githubusercontent.com/assets/9538395/6335854/0a31cdb4-bb64-11e4-9bc8-33ba661437b4.png)

**Comment by ryanbrownhill** [comment]
![screen shot 2015-02-23 at 1 58 55 pm](https://cloud.githubusercontent.com/assets/9538395/6335865/219215f4-bb64-11e4-915c-6b253b77ef84.png)

**Comment by una** [comment]
how would you feel if I removed the underlines from links? especially with your twitter handle having an underscore in it?

**Comment by una** [comment]
headers with #10 

![screen shot 2015-02-23 at 2 52 01 pm](https://cloud.githubusercontent.com/assets/1693164/6336894/96e83796-bb6b-11e4-9a5f-30cbb8d40dd8.png)

**Comment by ryanbrownhill** [comment]
@una I noticed Nexa Thin isn't in your screen cap - have you pulled the latest typefaces?
You also might need to install them as well

**Comment by una** [comment]
@ryanbrownhill yep! good catch. 

I need to import the typography into the CSS. I will do that with my next PR, making an issue now to address the Sass architecture :+1:

**Comment by una** [comment]
What I like about the long fading shadow is that it is very super-hero-esque

**Comment by ryanbrownhill** [comment]
@una Yeah I like the long fading shadows just think we should change the type color the darker blue to have more contrast. Or we could try an orange shadow - I will experiment with it , when I am doing #6 -Color Pallete.

**Comment by ryanbrownhill** [comment]
@una  
If we embed the typefaces we have then we can call this one closed.

**Comment by una** [comment]
Moved to #11
