### ISSUE TITLE
Nexa Not Working

### ISSUE THREAD

**Issue by ryanbrownhill** [una/slides-SXSW-2015#22]
The Nexa Typeface isn't working on my machine - I mentioned it in #21 but decided to make an Issue for it.

**Comment by una** [comment]
I updated the gulpfile to build out fonts. Did you pull? It may be a linking issue

**Comment by ryanbrownhill** [comment]
I will pull again and try

**Comment by ryanbrownhill** [comment]
@una still not luck - I looked at the gulpfile.js on the repo and don't see any font actions? maybe push again IDK? Might be an error on my end.
