### ISSUE TITLE
Color Pallete

### ISSUE THREAD

**Issue by ryanbrownhill** [una/slides-SXSW-2015#6]
Still not 100% on the current color palette maybe we can try something else. I did some experimenting:

Option A:
![screen shot 2015-02-22 at 7 42 32 pm](https://cloud.githubusercontent.com/assets/9538395/6322017/35139410-bad1-11e4-8f28-98025984ea1e.png)

![screen shot 2015-02-22 at 8 33 29 pm](https://cloud.githubusercontent.com/assets/9538395/6322056/2fec11e6-bad2-11e4-991f-f8f450088769.png)

Option B:
![screen shot 2015-02-22 at 7 42 39 pm](https://cloud.githubusercontent.com/assets/9538395/6322018/3515bba0-bad1-11e4-9eca-6245138cf8e2.png)

![screen shot 2015-02-22 at 8 37 08 pm](https://cloud.githubusercontent.com/assets/9538395/6322071/aa844734-bad2-11e4-9f3c-ee4d02ac6ad3.png)

**Comment by una** [comment]
I like the dark background but I think maybe switch out the teals for the first set

**Comment by ryanbrownhill** [comment]
![screen shot 2015-02-23 at 2 01 44 pm](https://cloud.githubusercontent.com/assets/9538395/6335919/85f74ad2-bb64-11e4-9f54-b89570c93da1.png)

Something like this maybe?
